#Yamamoto (2020, p. 233)
install.packages("moments")
install.packages("sp")
install.packages("RANN")
install.packages("sfsmisc")
install.packages("interp")
install.packages("raster")
install.packages("gstat")
install.packages("svDialogs")
