#Yamamoto (2020, p. 252)
setwd("C:\\geoEspacial\\DataR\\reta")
reta <- read.csv("reta.csv",sep=";",header=TRUE)
#setwd("C:\\geoEspacial\\DataR\\tempo")
#pdf("Fig8_20.pdf",width=5,height=5)
lm(reta$Y~reta$X)
plot(reta$X,reta$Y,pch=16,cex=1.5,col="blue",xlab="X",ylab="Y")
abline(lm(reta$Y~reta$X))
#dev.off()
