#Yamamoto (2020, p. 237)
setwd("C:\\geoEspacial\\DataR\\simetrica225")
dados <- read.csv("simetrica225.csv",sep=";",header=TRUE)
#setwd("C:\\geoEspacial\\DataR\\tempo")
#pdf("Fig8_8.pdf",width=5,height=5)
hist(dados$Zgauss)
#dev.off()